-1. Every order joined to customer name, product name, category, and a calculated line_revenue (quantity times ----unit_price).
--In simple terms this query joins the orders, customers, and products tables to show order details. 
--It also calculates the revenue for each order by multiplying quantity by unit price.


SELECT
    o.order_id,
    o.order_date,
    c.customer_name,
    p.product_name,
    p.category,
    o.quantity,
    p.unit_price,
    o.quantity * p.unit_price AS line_revenue
FROM DE_PROJECT1.DBO.orders o
JOIN DE_PROJECT1.DBO.customers c
    ON o.customer_id = c.customer_id
JOIN DE_PROJECT1.DBO.products p
    ON o.product_id = p.product_id
ORDER BY o.order_id;


--2.Total revenue per customer.
--This query calculates the total revenue generated by each customer by adding the revenue from their orders.


SELECT
    c.customer_id,
    c.customer_name,
    SUM(o.quantity * p.unit_price) AS total_revenue
FROM DE_PROJECT1.DBO.orders o
JOIN DE_PROJECT1.DBO.customers c
    ON o.customer_id = c.customer_id
JOIN DE_PROJECT1.DBO.products p
    ON o.product_id = p.product_id
GROUP BY
    c.customer_id,
    c.customer_name
ORDER BY total_revenue DESC;



--Total revenue per product category.
--This query calculates the total revenue generated by each product category.

SELECT
    p.category,
    SUM(o.quantity * p.unit_price) AS total_revenue
FROM DE_PROJECT1.DBO.orders o
JOIN DE_PROJECT1.DBO.products p
    ON o.product_id = p.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;



--Top 5 customers by total spend.
--This query finds the five customers who spent the most by calculating and ranking their total spending.

SELECT
    c.customer_id,
    c.customer_name,
    SUM(o.quantity * p.unit_price) AS total_spend
FROM DE_PROJECT1.DBO.orders o
JOIN DE_PROJECT1.DBO.customers c
    ON o.customer_id = c.customer_id
JOIN DE_PROJECT1.DBO.products p
    ON o.product_id = p.product_id
GROUP BY
    c.customer_id,
    c.customer_name
ORDER BY total_spend DESC
LIMIT 5;